[vep]
## Input/output format
format vcf
vcf true

## Output content
symbol true
protein true
canonical true
terms SO
tsl true
biotype true
hgvs true
gene_version true
transcript_version true

## Cache and FASTA setup
offline true
fasta /data/ensembl-vep/vep_cache/homo_sapiens/113_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa
dir_cache /data/ensembl-vep/vep_cache
dir_plugins /data/ensembl-vep/vep_cache/Plugins
cache true

## Plugins
plugin Frameshift
plugin Wildtype
